StudentsHealth/StudentsHealth/Controllers/DuyuruController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentsHealth.Models;
using System.IO;

namespace StudentsHealth.Controllers
{
    public class DuyuruController : Controller
    {
        public string UploadImage(HttpPostedFileBase image)
        {
            var imagePath = Path.Combine(Server.MapPath("~/Content/template/img/"), image.FileName);
            var imageUrl = Path.Combine("~/Content/template/img/", image.FileName);
            while (System.IO.File.Exists(imagePath))
            {
                Random rnd = new Random();
                string fileName = Path.GetFileNameWithoutExtension(image.FileName) + "-" + rnd.Next(0, 999) + Path.GetExtension(image.FileName);
                imagePath = Path.Combine(Server.MapPath("~/Content/template/img/"), fileName);
                imageUrl = Path.Combine("~/Content//template/img/", fileName);
            }
            image.SaveAs(imagePath);
            return imageUrl;
        }
        private StudentsHealthEntities db = new StudentsHealthEntities();

        // GET: Duyuru
        public ActionResult Index()
        {
            var duyuru = db.Duyuru.Include(d => d.Kategori).Include(d => d.Kategori1);
            ViewBag.DuyuruListe = db.Duyuru.ToList();
            return View(duyuru.ToList());
        }
        

        // GET: Duyuru/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.DuyuruListe = db.Duyuru.ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Duyuru duyuru = db.Duyuru.Find(id);
            if (duyuru == null)
            {
                return HttpNotFound();
            }
            return View(duyuru);
        }
       

        // GET: Duyuru/Create
        public ActionResult Create()
        {

            ViewBag.DuyuruListe = db.Duyuru.ToList();
            ViewBag.Kategori = Kategoriler();
            ViewBag.KategoriID = new SelectList(db.Kategori, "KategoriID", "Text");
            ViewBag.KategoriID = new SelectList(db.Kategori, "KategoriID", "Text");
            return View();
        }
        public List<KategoriViewModel> Kategoriler()
        {
            var kategoriler = db.Kategori.Where(x => x.UstKategoriID == null).ToList();
            List<KategoriViewModel> kategoriList = new List<KategoriViewModel>();
            foreach (var item in kategoriler)
            {
                kategoriList.Add(new KategoriViewModel()
                {
                    Kategori = item,
                    AltKategoriler = db.Kategori.Where(x => x.UstKategoriID == item.KategoriID).ToList(),
                    YanKategoriler = db.Kategori.Where(y => y.UstKategoriID > 5).ToList()
                });
            }
            return kategoriList;
        }
        

        // POST: Duyuru/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DuyuruID,İmageUrl,Baslik,İcerik,KategoriID")] Duyuru duyuru ,HttpPostedFileBase image)
        {

            ViewBag.DuyuruListe = db.Duyuru.ToList();
            if (ModelState.IsValid)
            {
                string imageUrl = UploadImage(image);
                duyuru.İmageUrl = imageUrl;
                db.Duyuru.Add(duyuru);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.KategoriID = new SelectList(db.Kategori, "KategoriID", "Text", duyuru.KategoriID);
            ViewBag.KategoriID = new SelectList(db.Kategori, "KategoriID", "Text", duyuru.KategoriID);
            return View(duyuru);
        }

        // GET: Duyuru/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.DuyuruListe = db.Duyuru.ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Duyuru duyuru = db.Duyuru.Find(id);
            if (duyuru == null)
            {
                return HttpNotFound();
            }
            ViewBag.KategoriID = new SelectList(db.Kategori, "KategoriID", "Text", duyuru.KategoriID);
            ViewBag.KategoriID = new SelectList(db.Kategori, "KategoriID", "Text", duyuru.KategoriID);
            return View(duyuru);
        }

        // POST: Duyuru/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DuyuruID,İmageUrl,Baslik,İcerik,KategoriID")] Duyuru duyuru,HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                string imageUrl = UploadImage(image);
                duyuru.İmageUrl = imageUrl;
                db.Entry(duyuru).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KategoriID = new SelectList(db.Kategori, "KategoriID", "Text", duyuru.KategoriID);
            ViewBag.KategoriID = new SelectList(db.Kategori, "KategoriID", "Text", duyuru.KategoriID);
            return View(duyuru);
        }

        // GET: Duyuru/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Duyuru duyuru = db.Duyuru.Find(id);
            if (duyuru == null)
            {
                return HttpNotFound();
            }
            return View(duyuru);
        }

        // POST: Duyuru/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Duyuru duyuru = db.Duyuru.Find(id);
            db.Duyuru.Remove(duyuru);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentsHealth/StudentsHealth/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentsHealth.Models;

namespace StudentsHealth.Controllers
{
    public class KategoriController : Controller
    {
        private StudentsHealthEntities db = new StudentsHealthEntities();

        // GET: Kategori
        public ActionResult Index()
        {
            return View(db.Kategori.ToList());
        }
       

        // GET: Kategori/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategori kategori = db.Kategori.Find(id);
            if (kategori == null)
            {
                return HttpNotFound();
            }
            return View(kategori);
        }

        // GET: Kategori/Create
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: Kategori/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KategoriID,Text,UstKategoriID")] Kategori kategori)
        {
            if (ModelState.IsValid)
            {
                db.Kategori.Add(kategori);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kategori);
        }

        // GET: Kategori/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategori kategori = db.Kategori.Find(id);
            if (kategori == null)
            {
                return HttpNotFound();
            }
            return View(kategori);
        }

        // POST: Kategori/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KategoriID,Text,UstKategoriID")] Kategori kategori)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kategori).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kategori);
        }

        // GET: Kategori/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategori kategori = db.Kategori.Find(id);
            if (kategori == null)
            {
                return HttpNotFound();
            }
            return View(kategori);
        }

        // POST: Kategori/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kategori kategori = db.Kategori.Find(id);
            db.Kategori.Remove(kategori);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentsHealth/StudentsHealth/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Students Health - Admin Paneli</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <header>
        <nav>
            <ul class="pagination">

                <li>@Html.ActionLink("Kullaniciları Yönet", "Index", "Kullanici")</li>
                <li>@Html.ActionLink("Duyuruları Düzenle", "Index", "Duyuru")</li>
                <li>@Html.ActionLink("Kategorileri Düzenle", "Index", "Kategori")</li>
            </ul>
        </nav>

    </header>      
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Students Health</p>
        </footer>
    </div>
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

StudentsHealth/StudentsHealth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>

<title>@ViewBag.Title - Students Health</title>
<meta charset="utf-8">

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Your description">
<meta name="keywords" content="Your keywords">
<meta name="author" content="Your name">
    <link rel="icon" href="@Url.Content("~/Content/template/")img/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="@Url.Content("~/Content/template/")img/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="~/Content/template/css/bootstrap.css" type="text/css" media="screen">
    <link rel="stylesheet" href="~/Content/template/css/responsive.css" type="text/css" media="screen">
    <link rel="stylesheet" href="~/Content/template/css/style.css" type="text/css" media="screen">
    
    
    

</head>
<body>
    <header>
        <div class="container">
            <div class="row">
                <div class="span10">
                    <div class="header-block clearfix">
                        <div class="clearfix header-block-pad">
                            <h1 class="brand"><a href="@Url.Content("~/Home/Index")"><img src="@Url.Content("~/Content/template/img/logo.png")" alt=""></a><span>Just Do İt</span></h1>
                            <form id="search-form" action="search.php" method="GET" accept-charset="utf-8" class="navbar-form">
                                <input type="text" name="s" onBlur="if(this.value=='') this.value=''" onFocus="if(this.value =='' ) this.value=''">
                                <a href="#" onClick="document.getElementById('search-form').submit()"></a>
                            </form>
                            <span class="contacts">Arama Hattı:  <span>+90 539 999 9999</span><br> 
                                <a href="@Url.Content("~/Home/Duyurular/24")">Örnek Sayfa</a>
                                <a href="@Url.Content("~/Home/Duyurular/20")">Örnek Sayfa2</a>
                                <a href="@Url.Content("~/Home/Duyurular/19")">Örnek Sayfa3</a>
                            </span>
                        </div>
                        <div class="navbar navbar_ clearfix">
                            <div class="navbar-inner navbar-inner_">
                                <div class="container">
                                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse_"></a>
                                    <div class="nav-collapse nav-collapse_ collapse">
                                        <ul class="nav sv-menu">                                           
                                             <li class="li-first"><a href="@Url.Content("~/Home/Index")">AnaSayfa</a></li>                                                                                                 
                                            <li class="sub-menu"><a href="">Zayıflama</a>
                                                <ul>
                                                    <li><a href="@Url.Content("~/Home/Duyurular/23")">Diyet</a></li>
                                                    <li><a href="@Url.Content("~/Home/Duyurular/24")">Spor</a></li>
                                                </ul>
                                            </li>
                                            <li class="sub-menu"><a href="">Sağlık</a>
                                                <ul>
                                                    <li>Beslenme<a href="@Url.Content("~/Home/Duyurular/25")"></a></li>
                                                    <li>Genel Sağlık<a href="@Url.Content("~/Home/Duyurular/26")"></a></li>
                                                </ul>
                                            </li>
                                            <li class="sub-menu"><a href="">Fitness</a>
                                                <ul>
                                                    <li>Genel Bilgiler<a href="@Url.Content("~/Home/Duyurular/27")"></a></li>
                                                    <li>Evde Vücut Geliştirme<a href="@Url.Content("~/Home/Duyurular/28")"></a></li>
                                                </ul>
                                            </li>
                                            <li><a href=""></a>Kaç Kalori?</li>
                                            <li class="sub-menu">
                                                <ul>
                                                    <li>Genel Bilgiler<a href="@Url.Content("~/Home/Duyurular/29")"></a></li>
                                                    <li>Evde Vücut Geliştirme<a href="@Url.Content("~/Home/Duyurular/30")"></a></li>
                                                </ul>
                                            </li>

                                          

                                            <li>Link 1</li>
                                        </ul>
                                    </div>                         
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    @*
                                                        *******************                         ÖNEMLİ AÇIKLAMA               *******************
                                                                   -----KATEGORİLERİN YERİNE SİTENİN DÜZGÜN ÇALIŞTIĞINI GÖSTERMEK İÇİN
                                                                                     HEADER KISMINA 3 TANE LİNK YAZDIK İNDİRDİĞİMİZ TEMPLATEDEN DOLAYI GÖRÜNTÜLENMİYOR
                                                        ------------------KATEGORİLERİ veri tabanından çekip yazdırmıştık fakat göstermiyor----------
                                                               KODLAR Çalışıyor Web Browserda " Sağ Tık/İncele dediğimizde  kod kısmında görünüyor
                                                                                                ama Görüntülemiyor
                                                                                    DEFAULT MVC TEMPLATE YÜKLÜ İKEN AŞAĞIDAKİ KOD ÇALIŞMAKTAYDI.
                                                                                  Menü HTML Kodlarıyla eklendiğindede menüler ve alt menüler çalışmıyor.
                                                                                       Muhtemelen temanın js veya css dosyalarıyla alakalı.
                                                                                                KODLAR AŞAĞIDADIR

                                                        @foreach (StudentsHealth.Models.KategoriViewModel item in ViewBag.Kategoriler)
        {
            if (item.AltKategoriler.Count == 0)
            {
                <li><a href="@Url.Content("/Home/Duyurular/" + item.Kategori.KategoriID)"></a></li>
            }
            else
            {
                <li class="sub-menu">
                    <ul>
                        @foreach (var item2 in item.AltKategoriler)
                        {
                            <li><a href="@Url.Content("/Home/Duyurular/" + item2.KategoriID)">@item2.Text</a></li>
                        }
                    </ul>
                </li>
            }
        }*@




<section class="main-content">

    @RenderBody()


    <footer>
        <p>&copy; @DateTime.Now.Year - Students Health</p>
    </footer>

</section>

    

  
    <script type="text/javascript" src="~/Content/template/js/jquery.js"></script>
    <script type="text/javascript" src="~/Content/template/js/jquery.easing.1.3.js"></script>
    <script src="~/Content/template/js/jquery.ui.totop.js" type="text/javascript"></script>
   
    @RenderSection("scripts", required: false)
    
   
  
  
       
    

</body>
</html>